name: CI

on: [pull_request]

jobs:
  ci:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install dependencies
        run: |
          brew install doxygen
          brew install graphviz

      - name: Create google-services.json
        run: |
          echo ${{ secrets.GOOGLE_SERVICES_JSON }} > samples/android/Assets/google-services.json

      - name: Build
        run: bash ./gradlew build
